language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "minious-github"
    token:
      secure: "2d7d3d005f62325cda00d2ac8bc9fe1c60b2e115"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'